Update test.py
To only return required fields added lines 48 - 70.  But gives   
File "test2.py", line 73, in <module>
    **member
KeyError: 'custom_8'